name: go_to_the_fucking_gym
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router:
  provider:
  intl:
  flutter_animate:
  retrofit:
  dio:
  json_annotation:
  table_calendar:
  fl_chart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  retrofit_generator:

flutter:
  uses-material-design: true
